type: "train"

# path
save_ckpt_dir: ./checkpoints
load_ckpt_path: ./checkpoints/pretrained/512-inpainting-ema.ckpt

model_cfg_path: ./configs/train/textdesign_sd_2.yaml
dataset_cfg_path: ./configs/dataset/st.yaml

# 
resume: False


# param
save_ckpt_freq: 1
num_workers: 0
batch_size: 8
base_learning_rate: 5.0e-5
shuffle: False

# runtime
lightning:
  max_epochs: 100
  accelerator: gpu
  strategy: ddp_find_unused_parameters_true
  accumulate_grad_batches: 4
  devices: [0,1,2,3]
  default_root_dir: ./logs
  profiler: simple 